# docker-compose.override.yml
# This file is for local development overrides - do not distribute it to my client.

services:
  postgres:
    # For local development, we use the standard public PostgreSQL image.
    # Migrations will be applied from the host machine after the container starts.
    image: postgres:16

  mindsdb:
    # For local development, we use the standard public MindsDB image.
    image: mindsdb/mindsdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # We mount our local configuration scripts into the container
    # to allow for hot-reloading if you change them.
    volumes:
      - ../AteraMindsDbMcpServer/deploy:/app/config
      - ./scripts/mindsdb-healthcheck.sh:/healthcheck.sh:ro
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  atera-dbsync:
    build:
      context: ../AteraMcpServer
      dockerfile: AteraDb.Sync/Dockerfile
    environment:
      - ConnectionStrings__AteraDb=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - SyncOptions__IncrementalSyncIntervalMinutes=${SYNC_INCREMENTAL_MINUTES:-5}
      - SyncOptions__TicketOnlySyncIntervalMinutes=${SYNC_TICKET_ONLY_MINUTES:-1440}
      - SyncOptions__TicketCommentsAlertsSyncIntervalMinutes=${SYNC_TICKET_COMMENTS_ALERTS_MINUTES:-10080}
      - OtlpExporter__Endpoint=